#!/bin/bash
# RAPP Shot installer — idempotent.
#   ./install.sh            install
#   ./install.sh --hotkeys  ...and register Hammerspoon hotkeys
set -uo pipefail
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
SH="${SHOT_HOME:-$HOME/.rappshot}"
say(){ printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok(){  printf '    \033[32m✓\033[0m %s\n' "$*"; }
warn(){ printf '    \033[33m!\033[0m %s\n' "$*"; }
die(){ printf '\033[1;31mfatal:\033[0m %s\n' "$*" >&2; exit 1; }

say "Toolchain"
command -v swiftc >/dev/null || die "swiftc not found — xcode-select --install"
ok "swiftc"
command -v screencapture >/dev/null && ok "screencapture" || die "screencapture missing"

say "Building the Swift shims"
for s in ocr annotate clip context; do
  if [ -x "$SRC/src/$s" ] && [ "$SRC/src/$s" -nt "$SRC/src/$s.swift" ]; then ok "$s (up to date)"
  else ( cd "$SRC/src" && swiftc -O -o "$s" "$s.swift" ) || die "failed to build $s"; ok "$s built"; fi
done

say "Directories"
mkdir -p "$SH/shots"; ok "$SH/shots"
if [ ! -f "$SH/redact-patterns.txt" ]; then
  cat > "$SH/redact-patterns.txt" <<'PAT'
# Extra regexes for `shot redact --auto`, one per line.
# The built-in set already covers emails, GitHub/OpenAI/AWS keys, JWTs,
# bearer tokens, labelled secrets, card-like numbers and SSN-like numbers.
# Add anything specific to you, e.g. an internal ticket format:
# INTERNAL-[0-9]{4}
PAT
  ok "redact-patterns.txt seeded"
else ok "redact-patterns.txt kept (yours)"; fi

say "CLI"
mkdir -p "$HOME/.local/bin"; ln -sfn "$SRC/shot" "$HOME/.local/bin/shot"
ok "$HOME/.local/bin/shot -> $SRC/shot"
case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) warn "add ~/.local/bin to your PATH" ;; esac

if [ "${1:-}" = "--hotkeys" ]; then
  say "Hammerspoon hotkeys"
  [ -d "$HOME/.hammerspoon" ] || die "Hammerspoon not installed"
  ln -sfn "$SRC/rappshot.lua" "$HOME/.hammerspoon/rappshot.lua"
  INIT="$HOME/.hammerspoon/init.lua"
  # NEVER append through a symlink. init.lua is often a symlink into ANOTHER
  # app's repo (RAPP Voice ships one), and appending would silently edit that
  # repo's tracked source. Materialise a real init.lua that requires both.
  if [ -L "$INIT" ]; then
    TARGET=$(readlink "$INIT")
    warn "init.lua is a symlink into $(basename "$(dirname "$TARGET")") — not editing that repo"
    rm "$INIT"
    {
      echo "-- Generated by rapp-shot install.sh."
      echo "-- init.lua used to be a symlink to:"
      echo "--   $TARGET"
      echo "-- It is now a real file so more than one RAPP app can load, and so no"
      echo "-- installer writes into another app's repository."
      echo "dofile(\"$TARGET\")"
      echo 'require("rappshot")'
    } > "$INIT"
    ok "init.lua materialised, still loading $(basename "$TARGET")"
  elif [ -f "$INIT" ]; then
    if grep -q 'require("rappshot")' "$INIT"; then ok "init.lua already requires rappshot"
    else printf '\nrequire("rappshot")\n' >> "$INIT"; ok "appended require(\"rappshot\")"; fi
  else
    printf 'require("rappshot")\n' > "$INIT"; ok "init.lua created"
  fi
  # reload in the background with a hard cap — a blocking `hs -c` can hang if
  # Hammerspoon is already mid-reload, and that stalled this installer once.
  if command -v hs >/dev/null; then
    ( hs -c 'hs.reload()' >/dev/null 2>&1 & sleep 6; kill %1 2>/dev/null ) >/dev/null 2>&1 || true
    ok "Hammerspoon reload requested"
  fi
  ok "hotkeys: cmd-shift-6 copy · cmd-shift-7 redact+copy · cmd-shift-8 text"
fi

say "Checking it works"
"$SRC/shot" doctor 2>&1 | sed 's/^/    /'
cat <<'NOTE'

============================================================
 RAPP Shot installed.
============================================================
 PERMISSION
  Screen Recording — grant it to your terminal (and to
  Hammerspoon if you use the hotkeys).

 THE ONE TO REMEMBER
  shot capture --auto-redact --copy
  ...finds secrets with OCR and paints them out OPAQUELY
  before the image ever reaches your clipboard.

 Shots live in ~/.rappshot/shots. Nothing is uploaded.
============================================================
NOTE
